
---
- name: Myplaybook
  hosts: all
  become: yes

  vars:
   mytext: "Hello world!"

  tasks:
  - name: Ping test
    ping:

  - name: Unregister server
    shell: echo Thist server {{ inventory_hostname }} was unregister from server, node name is  {{ ansible_nodename }} >> /home/lo.txt
    delegate_to: 127.0.0.1

  - name: Update DB
    shell: echo examlpe_update_DB
    run_once: true ## Запускает только на одном сервере, по порядку в списке hosts

  - name: Create file1
    copy: 
      dest: /home/file1.txt
      content:
         This is file1
         hi with var {{ mytext }}
    delegate_to: LinuxVM3

  - name: Create file2
    copy:
      dest: /home/file2.txt
      content:
         This is file2
         hi with var {{ mytext }} 

  - name: Reboot servers
    shell: sleep 3 && reboot now
    async: 1
    poll: 0

  - name: Wait until server come up online
    wait_for:
      host: "{{ inventory_hostname }}"
      state: started
      delay: 5
      timeout: 40
    delegate_to: 127.0.0.1