
---
- name: Install nginx and upload webpage
  hosts: all
  become: true

  vars:
    source_file: ./website/index.html
    destin_file: /var/www/html

  tasks:
  - name: Check and prind LINUX version
    debug: var=ansible_os_family

  - block: #=====Block for Debian=====

     - name: Install nginx webserver for Debian
       apt: name=nginx state=latest

     - name: Copy webpage to servers
       copy: src={{ source_file }} dest={{ destin_file }} mode=0555
       notify: Restart nginx

     - name: Start webserver and make it enable on boot
       service: name=nginx state=started enabled=yes
    when: ansible_os_family == "Debian"

  handlers:
  - name: Restart nginx
    service: name=nginx state=restarted